name: KrimBuy
main: de.bdh.kb2.Main
version: 2.3
authors: [wmchris]
permissions:
    kb.buy:
        description: User permissions for buy
        default: op
    kb.upgrade:
        description: User permissions for upgrade
        default: op
    kb.create:
        description: admin permissions to sell
        default: op
    kb.build:
        description: Allowed to build
        default: op
    kb.chest:
        description: Allowed to open chests
        default: op
    kb.nochest:
        description: Not Allowed to open chests
        default: op
    kb.w:
        description: Allowed to interact with everything
        default: op
    kb.teleport:
        description: Allowed to teleport to a free lot with price 0
        default: op
    kb.teleport.all:
        description: Allowed to teleport to a free lot with any price
        default: op
    kb.admin:
        description: Kann die BrauTec Limits umgehen
        default: op
    kab.build:
        description: Allowed to build (master)
        default: op
    kab.interact:
        description: Allowed to Interact (master)
        default: op
depend: [Vault]
commands:
    buyGS:
         description: Kaufe das GS
         usage: /kaufeGS
    upgradeGS:
         description: Erweitere das GS
         usage: /upgradeGS
    passwortGS:
         description: Setze ein PW auf das GS
         usage: /passwortGS PW
    passGS:
         description: Setze ein PW auf das GS
         usage: /passGS PW
    sellGS:
         description: Verkaufe dein Grundstueck
         usage: /sellGS
    mineGS:
         description: Kompass zeigt auf dein Grundstueck
         usage: /mineGS TYP
    useGS:
         description: Gib ein Passwort fuer ein Grunstueck ein
         usage: /useGS PW
    listGS:
         description: Gibt alle Regionen an gegebener Position / des Spielers aus
         usage: /listGS NAME
    delGS:
         description: Loescht eine Region nach ID
         usage: /delGS ID
    giveGS:
         description: Gibt das GS einem Spieler / Befreit es
         usage: /giveGS Optional_User
    nextGS:
         description: Fuehrt dich zum naechsten freien GS
         usage: /nextGS TYP
    tpGS:
         description: Teleportiert dich zur ID
         usage: /tpGS ID
    nolooseGS:
         description: Der Spieler verliert nicht sein GS - auch wenn er zu lange offline ist
         usage: /nolooseGS PLAYER
    neverlooseGS:
         description: Der Spieler verliert nicht sein GS - auch wenn er zu lange offline ist
         usage: /nolooseGS PLAYER
    makesell:
         description: make it sellable
         usage: /makesell amount
    kbruleset:
         description: setze das ruleset
         usage: /kbruleset REGELNAME
    kbupdate:
         description: aktualisiere das Grundstueck
         usage: /kbupdate
    dellallGS:
         description: entfernt alle Grundstuecke eines Typs
         usage: /dellallGS Typ
    kbreload:
         description: lade kb neu
         usage: /kbreload